
import sys
import idna
import requests
import argparse

parser = argparse.ArgumentParser(
    description="Creates valid_tld.js using a TLD list txt",
)
parser.add_argument(
    "-u","--url", type=str,
    default="http://data.iana.org/TLD/tlds-alpha-by-domain.txt"
)
parser.add_argument(
    "-o","--out", type=str,
    default="shortsearch/scripts/common/valid_tld.js"
)
parser.add_argument("-p","--pack", type=int, default=20)
args = parser.parse_args()

tldTxtUrl = args.url
pack = args.pack

r = requests.get(tldTxtUrl)
if (not r.ok):
    print(f'Could not get "{tldTxtUrl}" code {r.status_code}:{r.reason}')
    sys.exit(1)

lines = r.text.lower().splitlines()
lines.sort()

with open(args.out, "w", encoding="utf-8") as f:
    f.write("//Do not edit this file, it is Autogenerated\n")
    f.write("globalThis.EXT_SHORTSEARCH_VALID_TLDS=[\n")

    i = 0
    for l in lines:
        l = l.strip()

        if (l.startswith("#") or l == ""): continue
        if (l.startswith("xn--")):
            l = f'{l}","{idna.decode(l)}'
            i += 1
        i += 1

        f.write(f'"{l}",')
    
        if (i >= pack):
            f.write("\n")
            i = 0

    f.write("];\n")
